# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cosa.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cosa.proto',
  package='tutorial',
  syntax='proto2',
  serialized_pb=_b('\n\ncosa.proto\x12\x08tutorial\"u\n\x07Mensaje\x12\r\n\x05group\x18\x01 \x02(\x08\x12\x16\n\x0eip_destination\x18\x02 \x02(\t\x12\x11\n\tid_sender\x18\x03 \x02(\t\x12\x11\n\tdata_type\x18\x04 \x02(\x08\x12\x0f\n\x07\x63ontent\x18\x05 \x02(\t\x12\x0c\n\x04\x64\x61te\x18\x06 \x02(\t')
)




_MENSAJE = _descriptor.Descriptor(
  name='Mensaje',
  full_name='tutorial.Mensaje',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group', full_name='tutorial.Mensaje.group', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_destination', full_name='tutorial.Mensaje.ip_destination', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_sender', full_name='tutorial.Mensaje.id_sender', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_type', full_name='tutorial.Mensaje.data_type', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='tutorial.Mensaje.content', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='tutorial.Mensaje.date', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['Mensaje'] = _MENSAJE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mensaje = _reflection.GeneratedProtocolMessageType('Mensaje', (_message.Message,), dict(
  DESCRIPTOR = _MENSAJE,
  __module__ = 'cosa_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Mensaje)
  ))
_sym_db.RegisterMessage(Mensaje)


# @@protoc_insertion_point(module_scope)
